//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.jayqqaa12.reader.ui.view.pop;

import android.content.Context;

public final class MenuPop_
    extends MenuPop
{

    private Context context_;

    private MenuPop_(Context context) {
        context_ = context;
        init_();
    }

    public static MenuPop_ getInstance_(Context context) {
        return new MenuPop_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
