//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.reader.ui.adapter;

import android.content.Context;

public final class FileAdapter_
    extends FileAdapter
{

    private Context context_;

    private FileAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static FileAdapter_ getInstance_(Context context) {
        return new FileAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
